name: best7product_assignment
description: A new Flutter project for an assignment at bes7product by Dheeraj.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^1.2.0
  get: ^4.6.5
  google_api_headers: ^1.0.0
  google_maps_flutter: ^2.3.1
  # google_maps_webservice_ex: ^0.0.1+2
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^1.0.1
  loading_animation_widget: ^1.2.0+4
  pinput: ^2.2.31
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
